# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8de8d0ad98ccfa374349fcdba9824dfc195bdf78328fa9e235e3b952d2d5b19a88175279d96cf56945a9aac53477bafd9575100b449bfc2ba9a5933f7aaddec3

test:
  secret_key_base: fbc39aac31427169be9a1dd6a5497aa49e58feeefedfe255255c6ce8b4f1ee183475da76e247fff3b4aab319339a67ccf566071cba5cf7c724bbb386e4c18cef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
